Model/ApiPayloadResponse.php
Also now drops empty text entries.
=> [ENG-151] Correct support for CDATA sections.

Entity/Stat.php, Model/ContactClientModel.php
Also rename the column for consistency.
=> Add index to utm Source in Cache.

Integration/ClientIntegration.php, Model/ApiPayload.php, Model/Schedule.php
=> [ENG-202] Prevent carry-over logs between leads.

Model/ApiPayloadResponse.php
Will no longer run the risk of missing data, respects the hierarchy
provided by flattening to a complete array using dot-notation for
nesting. Can be reused in mustache tags.
=> [ENG-205] Improve support for hierarchical client data.

Controller/AjaxController.php, Entity/File.php, Entity/FileRepository.php, Integration/ClientIntegration.php, Model/FilePayload.php
This PR fixes a number of bugs introduced yesterday and adds file payload test support (the Test button now works).
=> [ENG-137] More file payload support.

Assets/json/file_payload.json, Model/FilePayload.php
Also change the default timeout to 30s.
=> Improve trapping for FTP/SFTP operations for test mode.

Command/SendContactCommand.php, Config/config.php, Controller/TimelineController.php, Helper/TokenHelper.php, Integration/ClientIntegration.php, Model/ApiPayload.php, Model/ApiPayloadOperation.php, Model/ApiPayloadRequest.php, Model/ApiPayloadResponse.php, Model/Cache.php
Improves usage of oauth Clients where tokens must be passed from one request to another in unusual ways. Token suggestions are now included in test JSON output.
=> [ENG-312] Contextual token bug

EventListener/ContactClientSubscriber.php
The currently merged version does not set the default date filter. This version does.
=> [ENG-374] Set default date range on first load

Command/SendContactCommand.php, Entity/Stat.php, Integration/ClientIntegration.php
This adds a new status for this scenario called “unpublished”
=> [ENG-383] Prevent sending contacts to an unpublished client.

Helper/TokenHelper.php
Should also boost performance slightly.
=> [ENG-432] Remove the possibility of attempting to render tokens on an array.

Entity/Stat.php
WARNING - merge PRIOR TO contact ledger bundle and WITH contact source bundle of the same ENG-433 ticket status.
=> [ENG-433] add contact_id index to help with utm_source inclusion dashboard reports

Config/config.php, Helper/TokenHelper.php
Also make sure to not break non-NR compatibility this time.
=> [ENG-445] Added logger interface for Mustache warnings.

Entity/ContactClient.php
=> [ENG-442] Allow Clients to be cloned again.

Assets/json/file_payload.json, Entity/File.php, Helper/TokenHelper.php, Model/FilePayload.php
=> [ENG-471] Add an easy way to exclude disallowed characters

Helper/FilterHelper.php
In other words, fields from the response bodies that contain dots or
some form of hierarchy will now validate normally.
=> [ENG-251] Support nested context for field validation.

Helper/FilterHelper.php
=> [ENG-251] Correction for root-level fields.

Entity/CacheRepository.php, Model/ApiPayloadResponse.php
They will now hit the replica database if present.
=> [ENG-665] Improve exclusivity check queries.

Model/FilePayload.php
Does not solve ENG-683, only adds debug into logs.
=> [ENG-683] Add debug log to help solve email with attachment issues on SES

Controller/TransactionsController.php, Security/Permissions/ContactClientPermissions.php, Views/Transactions/index.html.php
Depends on https://github.com/TheDMSGroup/mautic-eb/pull/77 in order to expose the export permissions,. Otherwise, fails gracefully without adding the permission.
=> [ENG-770] Allows transaction exports to be disabled on Roles

Integration/ClientIntegration.php
this should push with PR 5 from DNC Bundle
=> add dispatcher to DNC Repo so event dispatch works

Integration/ClientIntegration.php
Supports queuing contacts into a later hour of the current day based on scheduling.
=> [ENG-888] Current-day schedule queue fix.

Integration/ClientIntegration.php
**Please be sure you are submitting this against the _master_ branch.**
[//]: # This Pull Request (Place an 'X' for each):
| Risk Level                                | No | Low | High |
| ----------------------------------------- | -- | --- | ---- |
| Alters Lead Data?                         | X   |     |      |
| Schema Change?                            | X   |     |      |
| Adds A Query or Modifies Existing Query?  | X   |     |      |
| Adds or Modifies Existing Auto-Enhancer?  | X   |     |      |
| Modifies Ingestion Process?               | X   |     |      |
| Modifies sendContact Data?                | X   |     |      |
[//]: # ( Required: )
=> [ENG-959] Notice only client "errors" not all other stat types.

Entity/EventRepository.php, EventListener/LeadTimelineSubscriber.php
**Please be sure you are submitting this against the _master_ branch.**
[//]: # This Pull Request (Place an 'X' for each):
| Risk Level                                | No | Low | High |
| ----------------------------------------- | -- | --- | ---- |
| Alters Lead Data?                         |  X  |     |      |
| Schema Change?                            |  X  |     |      |
| Adds A Query or Modifies Existing Query?  |    |  X   |      |
| Adds or Modifies Existing Auto-Enhancer?  |  X  |     |      |
| Modifies Ingestion Process?               |  X  |     |      |
| Modifies sendContact Data?                |  X  |     |      |
[//]: # ( Required: )
Fixes Client events being shown on every page when viewing a Contact's Event history in pagination.
=> [ENG-975] Duplicated Source and Client events shown when a Contact has multiple pages of events.

Helper/DateFormatHelper.php
**Please be sure you are submitting this against the _master_ branch.**
[//]: # This Pull Request (Place an 'X' for each):
| Risk Level                                | No | Low | High |
| ----------------------------------------- | -- | --- | ---- |
| Alters Lead Data?                         |    |     |      |
| Schema Change?                            |    |     |      |
| Adds A Query or Modifies Existing Query?  |    |     |      |
| Adds or Modifies Existing Auto-Enhancer?  |    |     |      |
| Modifies Ingestion Process?               |    |     |      |
| Modifies sendContact Data?                |    |     |      |
[//]: # ( Required: )
Needs discussion and planning before merge.
=> [ENG-1034] Format datetime filters as destination timezones
